-- Loan
CREATE TABLE loan_types(
  id int NOT NULL AUTO_INCREMENT,
  loan_name varchar(100) NOT NULL unique DEFAULT 0,
  min_amount float NOT NULL,
  max_amount float NOT NULL,
  descriptions text,
  status_id int NOT NULL DEFAULT 1,
  generated_id varchar(80) NOT NULL UNIQUE DEFAULT '0',
  created_by int NOT NULL DEFAULT 0,
  modified_by int NOT NULL DEFAULT 0,
  date_created date NOT NULL,
  time_created time NOT NULL,
  updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_status INT NOT NULL DEFAULT 0,
  deleted_by INT NOT NULL DEFAULT 0,  
  PRIMARY KEY(id)
);

CREATE TABLE loan_requests(
  id int NOT NULL AUTO_INCREMENT,
  loan_type_id int NOT NULL DEFAULT 0,
  request_amount float NOT NULL,
  amount_paid float NOT NULL,
  userid int NOT NULL DEFAULT 0,
  attended_by int NOT NULL DEFAULT 0,
  year_apply varchar(20) NOT NULL DEFAULT 0,
  month_apply varchar(20) NOT NULL DEFAULT 0,
  day_apply varchar(20) NOT NULL DEFAULT 0,
  year_expire varchar(20) NOT NULL DEFAULT 0,
  month_expire varchar(20) NOT NULL DEFAULT 0,
  day_expire varchar(20) NOT NULL DEFAULT 0,
  duration varchar(20) NOT NULL DEFAULT 0,
  purpose_of_loan text,
  user_comment text,
  admin_comment text,
  payment_status int NOT NULL DEFAULT 0,
  approval_status int NOT NULL DEFAULT 0,
  request_status int NOT NULL DEFAULT 0,
  paid_status int NOT NULL DEFAULT 0,
  status_id int NOT NULL DEFAULT 1,
  generated_id varchar(80) NOT NULL UNIQUE DEFAULT '0',
  request_id varchar(80) NOT NULL,
  expire_date date NOT NULL,
  created_by int NOT NULL DEFAULT 0,
  modified_by int NOT NULL DEFAULT 0,
  date_created date NOT NULL,
  time_created time NOT NULL,
  updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_status INT NOT NULL DEFAULT 0,
  deleted_by INT NOT NULL DEFAULT 0,  
  PRIMARY KEY(id), 
  FOREIGN KEY(userid) REFERENCES user_record(id)
);


CREATE TABLE loan_guarantors(
  id int NOT NULL AUTO_INCREMENT,
  userid int NOT NULL DEFAULT 0,
  request_id varchar(80) NOT NULL,
  service_id int NOT NULL DEFAULT 0,
  title varchar(30) NOT NULL,
  fullname varchar(100) NOT NULL,
  phone_code varchar(20) NOT NULL,
  phone varchar(80) NOT NULL,
  email varchar(100) NOT NULL,
  occupation varchar(100) NOT NULL,
  relationship int NOT NULL DEFAULT 0,
  homeAddress text NOT NULL,
  workAddress text NOT NULL,
  attachment int NOT NULL DEFAULT 0,
  status_id int NOT NULL DEFAULT 1,
  created_by int NOT NULL DEFAULT 0,
  modified_by int NOT NULL DEFAULT 0,
  date_created date NOT NULL,
  time_created time NOT NULL,
  updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_status INT NOT NULL DEFAULT 0,
  deleted_by INT NOT NULL DEFAULT 0,  
  PRIMARY KEY(id),
  FOREIGN KEY(userid) REFERENCES user_record(id)
);

CREATE TABLE savings(
  id int NOT NULL AUTO_INCREMENT,
  amounts float NOT NULL,
  personal_id varchar(80) NOT NULL,
  userid int NOT NULL DEFAULT 0,
  save_year varchar(20) NOT NULL DEFAULT 0,
  save_month varchar(20) NOT NULL DEFAULT 0,
  save_day varchar(20) NOT NULL DEFAULT 0,
  comments text,
  approval_status int NOT NULL DEFAULT 0,
  status_id int NOT NULL DEFAULT 1,
  generated_id varchar(80) NOT NULL UNIQUE DEFAULT '0',
  created_by int NOT NULL DEFAULT 0,
  modified_by int NOT NULL DEFAULT 0,
  date_created date NOT NULL,
  time_created time NOT NULL,
  updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_status INT NOT NULL DEFAULT 0,
  deleted_by INT NOT NULL DEFAULT 0,  
  PRIMARY KEY(id)
);
CREATE TABLE loan_budgets (
  id int NOT NULL AUTO_INCREMENT,
  amounts float NOT NULL,
  year_apply varchar(20) NOT NULL DEFAULT 0,
  status_id int NOT NULL DEFAULT 1,
  generated_id varchar(80) NOT NULL UNIQUE DEFAULT '0',
  created_by int NOT NULL DEFAULT 0,
  modified_by int NOT NULL DEFAULT 0,
  date_created date NOT NULL,
  time_created time NOT NULL,
  updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_status INT NOT NULL DEFAULT 0,
  deleted_by INT NOT NULL DEFAULT 0,  
  PRIMARY KEY(id)
);

CREATE TABLE loan_payments (
  id int NOT NULL AUTO_INCREMENT,
  userid int NOT NULL DEFAULT 0,
  amounts float NOT NULL DEFAULT 0,
  personal_id varchar(80) NOT NULL,
  pay_year varchar(20) NOT NULL DEFAULT 0,
  pay_month varchar(20) NOT NULL DEFAULT 0,
  pay_day varchar(20) NOT NULL DEFAULT 0,
  comments text,
  status_id int NOT NULL DEFAULT 1,
  generated_id varchar(80) NOT NULL UNIQUE DEFAULT '0',
  date_created date NOT NULL,
  time_created time NOT NULL,
  updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_status INT NOT NULL DEFAULT 0,
  deleted_by INT NOT NULL DEFAULT 0,  
  PRIMARY KEY(id),
  FOREIGN KEY(personal_id) REFERENCES user_record(personal_id)
);
